# Generated by Django 4.1.7 on 2023-03-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsmodel',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
