# Generated by Django 4.1.7 on 2023-04-13 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogsmodel_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogsModel',
        ),
    ]
