# Generated by Django 4.1.7 on 2023-04-13 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogsModel',
        ),
    ]
