# Generated by Django 4.1.7 on 2023-04-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_blogsmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsmodel',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='blog_images/'),
        ),
    ]
